"""create_created_at_updated_at_table_point_turism

Revision ID: 0278d264f413
Revises: 9c48931d875c
Create Date: 2025-10-28 00:54:11.768262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0278d264f413'
down_revision: Union[str, Sequence[str], None] = '9c48931d875c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_turisms', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('point_turisms', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point_turisms', 'updated_at')
    op.drop_column('point_turisms', 'created_at')
    # ### end Alembic commands ###
