"""alter table point_turism with category id

Revision ID: 7274c420d9cb
Revises: 4ed05f6cc438
Create Date: 2025-10-28 14:23:20.982283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7274c420d9cb'
down_revision: Union[str, Sequence[str], None] = '4ed05f6cc438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_turisms', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'point_turisms', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'point_turisms', type_='foreignkey')
    op.drop_column('point_turisms', 'category_id')
    # ### end Alembic commands ###
