"""alter table turism point with city

Revision ID: 79a60dc506cd
Revises: 9c5cbd3bc634
Create Date: 2025-10-29 19:19:00.409949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a60dc506cd'
down_revision: Union[str, Sequence[str], None] = '9c5cbd3bc634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_turisms', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key('point_turisms_city_id_fkey', 'point_turisms', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('point_turisms_city_id_fkey', 'point_turisms', type_='foreignkey')
    op.drop_column('point_turisms', 'city_id')
    # ### end Alembic commands ###
