"""Update album model: remove title and description, add point_turism_id

Revision ID: 07028a88b52d
Revises: 784a034a664e
Create Date: 2026-01-06 01:17:13.515830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07028a88b52d'
down_revision: Union[str, Sequence[str], None] = '784a034a664e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('point_turism_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'albums', 'point_turisms', ['point_turism_id'], ['id'])
    op.drop_column('albums', 'description')
    op.drop_column('albums', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('albums', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.drop_column('albums', 'point_turism_id')
    # ### end Alembic commands ###
