"""albums update

Revision ID: 955aafcc9507
Revises: 07028a88b52d
Create Date: 2026-01-06 01:38:12.306036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '955aafcc9507'
down_revision: Union[str, Sequence[str], None] = '07028a88b52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album_images')
    op.add_column('albums', sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=False))
    op.alter_column('albums', 'point_turism_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('albums', 'point_turism_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('albums', 'image_urls')
    op.create_table('album_images',
    sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('album_images_album_id_fkey')),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('album_images_image_id_fkey')),
    sa.PrimaryKeyConstraint('album_id', 'image_id', name=op.f('album_images_pkey'))
    )
    # ### end Alembic commands ###
